language: java
# sudo: true [no effect]
dist: trusty
jdk: openjdk11
before_install:
  - chmod +x mvnw
script:
  - ./mvnw clean install test -B
deploy:
  provider: heroku
  on:
    branch: master
  api_key:
    secure: "j/rWn3hvfPFfGg3/Pi47GMXbTRqxFaXbhXw1H0HJz1OjogEKJBBl9kt7c/0XOnxzcitpx+btJt3K1vNR1fwWKW50RKy34e93knxITQGMk0+PAnLvIVwvklIwHDg2fsqpzju1PIWGw1S95Dhh8+R/jXd6rWVYcNWcuO/9g2xetX1KRhApcXQnudp/Ofz+z8IiFhP/xQ5I/97Pr8P3rvCaVfaLJOREboeWsShqdGHnIYmBBaiu/EMstbjz/GC/TgrO1IXDleo/owpz42Qo+ra+2b2BVNkJRpuiQSxI4yK5iuiR5V8i36WIOW9r5t5cvi+uImblEcNaE45hqIo7esobEcGmoWYzmEMIQuyk50zH3TkE0xi0xUxRSp1nTrnEBiO9aMeqif2Yfq1QeoGYJV/f7ZX70ZzQebheqltavfw/OnWqDTNdWHFigVxZQ/L1vNhpAn8ZtMC/53NPc8lpmiWQNXBxDZRv0n12SgHHnQf1vg6wpaSGNUbfCzMIPWINFQgVCOxstleixyChcG1bYeaBHyLwu6Iun1bbDDGAPU16P7o9s55p9Oj+5Z7yq4sPMtJ6zuyOsYyd0Sw7ckz7htoLc/NJs8l8j4+sn163y7QSlUG8KdPghsEhklTyGMOrT7GQPsf7SI+06DTie8kHaT3MpChVxt2y5tE8iefsLldLiE0="
  app:
    master: repo-example-h
    production: repo-exaple-h
notifications:
  webhooks: https://travis-for-jira-prod.toolsplus.app/travis/notifications?token=50ce1d9a-2267-343b-a6dd-18cccf3af5ce
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always

# travis encrypt $(heroku auth:token) --com    
