language: java
sudo: true
dist: trusty
jdk: openjdk11
before_install:
  - chmod +x mvnw
script:
  - ./mvnw clean install -B
deploy:
  provider: heroku
  on:
    branch: master
  api_key:
    secure: 451d16db-3bb2-4824-a04e-de9c52555826
  app:
    master: repo-example
    production: repo-exaple-h