language: java
sudo: true
dist: trusty
jdk: openjdk11
before_install:
  - chmod +x mvnw
script:
  - ./mvnw clean install -B
deploy:
  provider: heroku
  on:
    branch: master
  api_key:
    secure: 5cdfe133-51e7-4abd-8ec7-f342be6ad9c4
  app:
    master: repo-example
    production: repo-exaple-h